# Generated by Django 6.0.3 on 2026-04-01 18:30

from django.db import migrations

def create_departments(apps, schema_editor):
    Department = apps.get_model('faculty', 'Department')
    depts = [
        {'department_id': 'MATH', 'name': 'Mathématiques', 'started_year': 2020},
        {'department_id': 'PHY', 'name': 'Physique', 'started_year': 2020},
        {'department_id': 'CHM', 'name': 'Chimie', 'started_year': 2020},
        {'department_id': 'INF', 'name': 'Informatique', 'started_year': 2020},
        {'department_id': 'BIO', 'name': 'Biologie', 'started_year': 2020},
        {'department_id': 'LNG', 'name': 'Langue & Communication', 'started_year': 2020},
    ]
    for d in depts:
        Department.objects.get_or_create(department_id=d['department_id'], defaults=d)


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_book_author_book_quantity_alter_book_publisher_and_more'),
    ]

    operations = [
        migrations.RunPython(create_departments)
    ]
