# Generated by Django 6.0.3 on 2026-04-01 18:37

from django.db import migrations
import datetime

def create_teachers(apps, schema_editor):
    Teacher = apps.get_model('faculty', 'Teacher')
    Department = apps.get_model('faculty', 'Department')
    
    teachers_data = [
        {'id': 'T-001', 'first_name': 'Karim', 'last_name': 'Benali', 'gender': 'Male', 'dept_code': 'MATH'},
        {'id': 'T-002', 'first_name': 'Fatima Zahra', 'last_name': 'El Idrissi', 'gender': 'Female', 'dept_code': 'PHY'},
        {'id': 'T-003', 'first_name': 'Youssef', 'last_name': 'Amrani', 'gender': 'Male', 'dept_code': 'INF'},
        {'id': 'T-004', 'first_name': 'Amina', 'last_name': 'Berrada', 'gender': 'Female', 'dept_code': 'CHM'},
        {'id': 'T-005', 'first_name': 'Omar', 'last_name': 'Chraibi', 'gender': 'Male', 'dept_code': 'BIO'},
        {'id': 'T-006', 'first_name': 'Sanae', 'last_name': 'Alaoui', 'gender': 'Female', 'dept_code': 'LNG'},
    ]
    
    for t in teachers_data:
        try:
            dept = Department.objects.get(department_id=t['dept_code'])
        except Department.DoesNotExist:
            dept = None
            
        Teacher.objects.get_or_create(
            teacher_id=t['id'],
            defaults={
                'first_name': t['first_name'],
                'last_name': t['last_name'],
                'gender': t['gender'],
                'date_of_birth': datetime.date(1980, 5, 14),
                'joining_date': datetime.date.today(),
                'qualification': "Doctorat d'État",
                'experience': '10 Ans',
                'mobile_number': '+212600000000',
                'address': 'Rabat, Maroc',
                'department': dept
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_populate_departments'),
    ]

    operations = [
        migrations.RunPython(create_teachers)
    ]
