# Generated by Django 6.0.3 on 2026-04-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_book_author_book_quantity_alter_book_publisher_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
