# Generated by Django 6.0.3 on 2026-04-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_populate_teachers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
