# Generated by Django 6.0.3 on 2026-04-02 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('Cours', 'Cours / Support'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques'), ('GitHub', 'Lien Projet GitHub'), ('Examen', "Annales d'Examen")], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/docs/')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='faculty.subject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.teacher')),
            ],
        ),
    ]
