# Generated by Django 6.0.3 on 2026-03-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_certificaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(default=20),
        ),
    ]
