# Generated by Django 6.0.3 on 2026-03-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_examresult_is_published_alter_exam_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='proposed_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
