# Generated by Django 6.0.3 on 2026-03-21 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_activity'),
        ('student', '0005_examresult_proposed_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeNegotiationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Accepté', 'Accepté'), ('Refusé', 'Refusé')], max_length=20)),
                ('original_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proposed_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_decided', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_history', to='student.examresult')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.teacher')),
            ],
        ),
    ]
