# Generated by Django 6.0.3 on 2026-03-21 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_gradenegotiationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='student_cards/photos/')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('Générée', 'Générée'), ('Refusée', 'Refusée')], default='En attente', max_length=20)),
                ('issued_card', models.FileField(blank=True, null=True, upload_to='student_cards/generated/')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
