# Generated by Django 6.0.3 on 2026-03-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentcardrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='rattrapage_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
