# Generated by Django 6.0.3 on 2026-04-01 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_delete_book'),
        ('student', '0008_examresult_rattrapage_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryClassRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_no', models.CharField(max_length=20)),
                ('reason', models.CharField(choices=[('Rattrapage', 'Rattrapage (Catch-up)'), ('Soutien', 'Soutien (Support)'), ('Examen', 'Examen (Exam)'), ('Autre', 'Autre (Other)')], max_length=50)),
                ('custom_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'In Progress'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.teacher')),
            ],
        ),
    ]
