# Generated by Django 6.0.3 on 2026-04-02 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_temporaryclassrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(auto_now_add=True)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Présent', 'Présent'), ('En retard', 'En retard')], default='Présent', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.attendancesession')),
            ],
            options={
                'unique_together': {('student', 'session')},
            },
        ),
    ]
