# Generated by Django 6.0.3 on 2026-03-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='extra_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
