# Generated by Django 6.0.3 on 2026-04-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_customuser_is_authorized_customuser_login_token_and_more'),
        ('home_auth', '0004_accountrequest_extra_info'),
    ]

    operations = [
    ]
