# Generated by Django 6.0.3 on 2026-04-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_notification_link_notification_notification_type_and_more'),
        ('home_auth', '0006_remove_customuser_is_authorized_and_more'),
    ]

    operations = [
    ]
