from django.db import migrations
import datetime

def load_data(apps, schema_editor):
    data = [
    {'model': 'faculty.Department', 'fields': {
        'id': 9,
        'department_id': 'D01',
        'name': 'Mathematiques',
        'started_year': 1990,
        'no_of_students': 0
    }},
    {'model': 'faculty.Department', 'fields': {
        'id': 10,
        'department_id': 'D02',
        'name': 'Physique',
        'started_year': 1990,
        'no_of_students': 0
    }},
    {'model': 'faculty.Department', 'fields': {
        'id': 11,
        'department_id': 'D03',
        'name': 'SVT',
        'started_year': 1990,
        'no_of_students': 0
    }},
    {'model': 'faculty.Department', 'fields': {
        'id': 12,
        'department_id': 'D04',
        'name': 'Chimie',
        'started_year': 1990,
        'no_of_students': 0
    }},
    {'model': 'faculty.Department', 'fields': {
        'id': 13,
        'department_id': 'D05',
        'name': 'Informatique',
        'started_year': 1990,
        'no_of_students': 0
    }},
    {'model': 'faculty.Department', 'fields': {
        'id': 14,
        'department_id': 'D06',
        'name': 'Langue et Communication',
        'started_year': 1990,
        'no_of_students': 0
    }},
    {'model': 'faculty.Department', 'fields': {
        'id': 15,
        'department_id': 'MATH',
        'name': 'Mathématiques',
        'started_year': 2020,
        'no_of_students': 0
    }},
    {'model': 'faculty.Department', 'fields': {
        'id': 16,
        'department_id': 'PHY',
        'name': 'Physique',
        'started_year': 2020,
        'no_of_students': 0
    }},
    {'model': 'faculty.Department', 'fields': {
        'id': 17,
        'department_id': 'CHM',
        'name': 'Chimie',
        'started_year': 2020,
        'no_of_students': 0
    }},
    {'model': 'faculty.Department', 'fields': {
        'id': 18,
        'department_id': 'INF',
        'name': 'Informatique',
        'started_year': 2020,
        'no_of_students': 0
    }},
    {'model': 'faculty.Department', 'fields': {
        'id': 19,
        'department_id': 'BIO',
        'name': 'Biologie',
        'started_year': 2020,
        'no_of_students': 0
    }},
    {'model': 'faculty.Department', 'fields': {
        'id': 20,
        'department_id': 'LNG',
        'name': 'Langue & Communication',
        'started_year': 2020,
        'no_of_students': 0
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 43,
        'user_id': 7,
        'teacher_id': 'T001',
        'first_name': 'Docteur',
        'last_name': 'Professeur 1',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 11,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 44,
        'user_id': 48,
        'teacher_id': 'T002',
        'first_name': 'Docteur',
        'last_name': 'Professeur 2',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 9,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 45,
        'user_id': 49,
        'teacher_id': 'T003',
        'first_name': 'Docteur',
        'last_name': 'Professeur 3',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 14,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 46,
        'user_id': 50,
        'teacher_id': 'T004',
        'first_name': 'Docteur',
        'last_name': 'Professeur 4',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 9,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 47,
        'user_id': 51,
        'teacher_id': 'T005',
        'first_name': 'Docteur',
        'last_name': 'Professeur 5',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 12,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 48,
        'user_id': 12,
        'teacher_id': 'T006',
        'first_name': 'Docteur',
        'last_name': 'Professeur 6',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 12,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 49,
        'user_id': 13,
        'teacher_id': 'T007',
        'first_name': 'Docteur',
        'last_name': 'Professeur 7',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 12,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 50,
        'user_id': 14,
        'teacher_id': 'T008',
        'first_name': 'Docteur',
        'last_name': 'Professeur 8',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 9,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 51,
        'user_id': 52,
        'teacher_id': 'T009',
        'first_name': 'Docteur',
        'last_name': 'Professeur 9',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 13,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 52,
        'user_id': 53,
        'teacher_id': 'T010',
        'first_name': 'Docteur',
        'last_name': 'Professeur 10',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 12,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 53,
        'user_id': 54,
        'teacher_id': 'T011',
        'first_name': 'Docteur',
        'last_name': 'Professeur 11',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 11,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 54,
        'user_id': 55,
        'teacher_id': 'T012',
        'first_name': 'Docteur',
        'last_name': 'Professeur 12',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 14,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 55,
        'user_id': 56,
        'teacher_id': 'T013',
        'first_name': 'Docteur',
        'last_name': 'Professeur 13',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 11,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 56,
        'user_id': 57,
        'teacher_id': 'T014',
        'first_name': 'Docteur',
        'last_name': 'Professeur 14',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 14,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 57,
        'user_id': 58,
        'teacher_id': 'T015',
        'first_name': 'Docteur',
        'last_name': 'Professeur 15',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 12,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 58,
        'user_id': 59,
        'teacher_id': 'T016',
        'first_name': 'Docteur',
        'last_name': 'Professeur 16',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 13,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 59,
        'user_id': 60,
        'teacher_id': 'T017',
        'first_name': 'Docteur',
        'last_name': 'Professeur 17',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 10,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 60,
        'user_id': 61,
        'teacher_id': 'T018',
        'first_name': 'Docteur',
        'last_name': 'Professeur 18',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 9,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 61,
        'user_id': 25,
        'teacher_id': 'T019',
        'first_name': 'Docteur',
        'last_name': 'Professeur 19',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 9,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 62,
        'user_id': 26,
        'teacher_id': 'T020',
        'first_name': 'Docteur',
        'last_name': 'Professeur 20',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 13,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 63,
        'user_id': 62,
        'teacher_id': 'T021',
        'first_name': 'Docteur',
        'last_name': 'Professeur 21',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 14,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 64,
        'user_id': 63,
        'teacher_id': 'T022',
        'first_name': 'Docteur',
        'last_name': 'Professeur 22',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 13,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 65,
        'user_id': 64,
        'teacher_id': 'T023',
        'first_name': 'Docteur',
        'last_name': 'Professeur 23',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 9,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 66,
        'user_id': 65,
        'teacher_id': 'T024',
        'first_name': 'Docteur',
        'last_name': 'Professeur 24',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 10,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 67,
        'user_id': 31,
        'teacher_id': 'T025',
        'first_name': 'Docteur',
        'last_name': 'Professeur 25',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 12,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 68,
        'user_id': 66,
        'teacher_id': 'T026',
        'first_name': 'Docteur',
        'last_name': 'Professeur 26',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 11,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 69,
        'user_id': 67,
        'teacher_id': 'T027',
        'first_name': 'Docteur',
        'last_name': 'Professeur 27',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 10,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 70,
        'user_id': 68,
        'teacher_id': 'T028',
        'first_name': 'Docteur',
        'last_name': 'Professeur 28',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 11,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 71,
        'user_id': 69,
        'teacher_id': 'T029',
        'first_name': 'Docteur',
        'last_name': 'Professeur 29',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 9,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 72,
        'user_id': 70,
        'teacher_id': 'T030',
        'first_name': 'Docteur',
        'last_name': 'Professeur 30',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 12,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 73,
        'user_id': 71,
        'teacher_id': 'T031',
        'first_name': 'Docteur',
        'last_name': 'Professeur 31',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 9,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 74,
        'user_id': 72,
        'teacher_id': 'T032',
        'first_name': 'Docteur',
        'last_name': 'Professeur 32',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 14,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 75,
        'user_id': 73,
        'teacher_id': 'T033',
        'first_name': 'Docteur',
        'last_name': 'Professeur 33',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 10,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 76,
        'user_id': 74,
        'teacher_id': 'T034',
        'first_name': 'Docteur',
        'last_name': 'Professeur 34',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 13,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 77,
        'user_id': 75,
        'teacher_id': 'T035',
        'first_name': 'Docteur',
        'last_name': 'Professeur 35',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 12,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 78,
        'user_id': 76,
        'teacher_id': 'T036',
        'first_name': 'Docteur',
        'last_name': 'Professeur 36',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 10,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 79,
        'user_id': 77,
        'teacher_id': 'T037',
        'first_name': 'Docteur',
        'last_name': 'Professeur 37',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 11,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 80,
        'user_id': 78,
        'teacher_id': 'T038',
        'first_name': 'Docteur',
        'last_name': 'Professeur 38',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 12,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 81,
        'user_id': 79,
        'teacher_id': 'T039',
        'first_name': 'Docteur',
        'last_name': 'Professeur 39',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 11,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 82,
        'user_id': 80,
        'teacher_id': 'T040',
        'first_name': 'Docteur',
        'last_name': 'Professeur 40',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': '0600000000',
        'joining_date': datetime.date(2010, 1, 1),
        'qualification': 'Doctorat',
        'experience': 'Professeur Habilité',
        'department_id': 13,
        'address': 'Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 83,
        'user_id': 2,
        'teacher_id': 'TCH-2',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': 9,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 84,
        'user_id': 3,
        'teacher_id': 'TCH-3',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 85,
        'user_id': 8,
        'teacher_id': 'TCH-8',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 86,
        'user_id': 9,
        'teacher_id': 'TCH-9',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 87,
        'user_id': 10,
        'teacher_id': 'TCH-10',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 88,
        'user_id': 11,
        'teacher_id': 'TCH-11',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 89,
        'user_id': 15,
        'teacher_id': 'TCH-15',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 90,
        'user_id': 16,
        'teacher_id': 'TCH-16',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 91,
        'user_id': 17,
        'teacher_id': 'TCH-17',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 92,
        'user_id': 18,
        'teacher_id': 'TCH-18',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 93,
        'user_id': 19,
        'teacher_id': 'TCH-19',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 94,
        'user_id': 20,
        'teacher_id': 'TCH-20',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 95,
        'user_id': 21,
        'teacher_id': 'TCH-21',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 96,
        'user_id': 22,
        'teacher_id': 'TCH-22',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 97,
        'user_id': 23,
        'teacher_id': 'TCH-23',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 98,
        'user_id': 24,
        'teacher_id': 'TCH-24',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 99,
        'user_id': 27,
        'teacher_id': 'TCH-27',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 100,
        'user_id': 28,
        'teacher_id': 'TCH-28',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 101,
        'user_id': 29,
        'teacher_id': 'TCH-29',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 102,
        'user_id': 30,
        'teacher_id': 'TCH-30',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 103,
        'user_id': 32,
        'teacher_id': 'TCH-32',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 104,
        'user_id': 33,
        'teacher_id': 'TCH-33',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 105,
        'user_id': 34,
        'teacher_id': 'TCH-34',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 106,
        'user_id': 35,
        'teacher_id': 'TCH-35',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 107,
        'user_id': 36,
        'teacher_id': 'TCH-36',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 108,
        'user_id': 37,
        'teacher_id': 'TCH-37',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 109,
        'user_id': 38,
        'teacher_id': 'TCH-38',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 110,
        'user_id': 39,
        'teacher_id': 'TCH-39',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 111,
        'user_id': 40,
        'teacher_id': 'TCH-40',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 112,
        'user_id': 41,
        'teacher_id': 'TCH-41',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 113,
        'user_id': 42,
        'teacher_id': 'TCH-42',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 114,
        'user_id': 43,
        'teacher_id': 'TCH-43',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 115,
        'user_id': 44,
        'teacher_id': 'TCH-44',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 116,
        'user_id': 45,
        'teacher_id': 'TCH-45',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 117,
        'user_id': 46,
        'teacher_id': 'TCH-46',
        'first_name': '',
        'last_name': '',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 1, 1),
        'mobile_number': 'A compléter',
        'joining_date': datetime.date(2026, 3, 21),
        'qualification': 'A compléter',
        'experience': 'A compléter',
        'department_id': None,
        'address': 'A compléter'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 118,
        'user_id': 539,
        'teacher_id': 'T-001',
        'first_name': 'Karim',
        'last_name': 'Benali',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 5, 14),
        'mobile_number': '+212600000000',
        'joining_date': datetime.date(2026, 4, 1),
        'qualification': "Doctorat d'État",
        'experience': '10 Ans',
        'department_id': 15,
        'address': 'Rabat, Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 119,
        'user_id': 540,
        'teacher_id': 'T-002',
        'first_name': 'Fatima Zahra',
        'last_name': 'El Idrissi',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 5, 14),
        'mobile_number': '+212600000000',
        'joining_date': datetime.date(2026, 4, 1),
        'qualification': "Doctorat d'État",
        'experience': '10 Ans',
        'department_id': 16,
        'address': 'Rabat, Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 120,
        'user_id': 541,
        'teacher_id': 'T-003',
        'first_name': 'Youssef',
        'last_name': 'Amrani',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 5, 14),
        'mobile_number': '+212600000000',
        'joining_date': datetime.date(2026, 4, 1),
        'qualification': "Doctorat d'État",
        'experience': '10 Ans',
        'department_id': 18,
        'address': 'Rabat, Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 121,
        'user_id': 542,
        'teacher_id': 'T-004',
        'first_name': 'Amina',
        'last_name': 'Berrada',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 5, 14),
        'mobile_number': '+212600000000',
        'joining_date': datetime.date(2026, 4, 1),
        'qualification': "Doctorat d'État",
        'experience': '10 Ans',
        'department_id': 17,
        'address': 'Rabat, Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 122,
        'user_id': 543,
        'teacher_id': 'T-005',
        'first_name': 'Omar',
        'last_name': 'Chraibi',
        'gender': 'Male',
        'date_of_birth': datetime.date(1980, 5, 14),
        'mobile_number': '+212600000000',
        'joining_date': datetime.date(2026, 4, 1),
        'qualification': "Doctorat d'État",
        'experience': '10 Ans',
        'department_id': 19,
        'address': 'Rabat, Maroc'
    }},
    {'model': 'faculty.Teacher', 'fields': {
        'id': 123,
        'user_id': 544,
        'teacher_id': 'T-006',
        'first_name': 'Sanae',
        'last_name': 'Alaoui',
        'gender': 'Female',
        'date_of_birth': datetime.date(1980, 5, 14),
        'mobile_number': '+212600000000',
        'joining_date': datetime.date(2026, 4, 1),
        'qualification': "Doctorat d'État",
        'experience': '10 Ans',
        'department_id': 20,
        'address': 'Rabat, Maroc'
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 125,
        'subject_id': 'SUB_MIP_S1_000',
        'name': 'Analyse 1',
        'class_name': 'MIP_S1',
        'department_id': 9,
        'teacher_id': 50
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 126,
        'subject_id': 'SUB_MIP_S1_001',
        'name': 'Algebre 1',
        'class_name': 'MIP_S1',
        'department_id': 9,
        'teacher_id': 44
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 127,
        'subject_id': 'SUB_MIP_S1_002',
        'name': 'Circuit electrique',
        'class_name': 'MIP_S1',
        'department_id': 10,
        'teacher_id': 59
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 128,
        'subject_id': 'SUB_MIP_S1_003',
        'name': 'Electricite',
        'class_name': 'MIP_S1',
        'department_id': 10,
        'teacher_id': 69
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 129,
        'subject_id': 'SUB_MIP_S1_004',
        'name': 'LC 1',
        'class_name': 'MIP_S1',
        'department_id': 14,
        'teacher_id': 63
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 130,
        'subject_id': 'SUB_MIP_S1_005',
        'name': 'Algorithme et Programmation 1',
        'class_name': 'MIP_S1',
        'department_id': 9,
        'teacher_id': 76
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 131,
        'subject_id': 'SUB_MIP_S2_006',
        'name': 'Analyse 2',
        'class_name': 'MIP_S2',
        'department_id': 9,
        'teacher_id': 60
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 132,
        'subject_id': 'SUB_MIP_S2_007',
        'name': 'Algebre 2',
        'class_name': 'MIP_S2',
        'department_id': 9,
        'teacher_id': 61
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 133,
        'subject_id': 'SUB_MIP_S2_008',
        'name': 'Thermodynamique',
        'class_name': 'MIP_S2',
        'department_id': 10,
        'teacher_id': 78
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 134,
        'subject_id': 'SUB_MIP_S2_009',
        'name': 'Mecanique du point',
        'class_name': 'MIP_S2',
        'department_id': 10,
        'teacher_id': 78
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 135,
        'subject_id': 'SUB_MIP_S2_010',
        'name': 'LC 2',
        'class_name': 'MIP_S2',
        'department_id': 14,
        'teacher_id': 63
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 136,
        'subject_id': 'SUB_MIP_S2_011',
        'name': 'Atomistique et thermochimie',
        'class_name': 'MIP_S2',
        'department_id': 12,
        'teacher_id': 67
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 137,
        'subject_id': 'SUB_MIP_S3_012',
        'name': 'Analyse 3',
        'class_name': 'MIP_S3',
        'department_id': 9,
        'teacher_id': 61
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 138,
        'subject_id': 'SUB_MIP_S3_013',
        'name': 'Statistique et proba',
        'class_name': 'MIP_S3',
        'department_id': 9,
        'teacher_id': 60
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 139,
        'subject_id': 'SUB_MIP_S3_014',
        'name': 'Reactivite chimique',
        'class_name': 'MIP_S3',
        'department_id': 12,
        'teacher_id': 48
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 140,
        'subject_id': 'SUB_MIP_S3_015',
        'name': 'LC 3',
        'class_name': 'MIP_S3',
        'department_id': 14,
        'teacher_id': 63
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 141,
        'subject_id': 'SUB_MIP_S3_016',
        'name': 'Mecanique de solide',
        'class_name': 'MIP_S3',
        'department_id': 10,
        'teacher_id': 66
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 142,
        'subject_id': 'SUB_MIP_S3_017',
        'name': 'Algo et program 2',
        'class_name': 'MIP_S3',
        'department_id': 9,
        'teacher_id': 67
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 143,
        'subject_id': 'SUB_MIP_S4_018',
        'name': 'Analyse 4',
        'class_name': 'MIP_S4',
        'department_id': 9,
        'teacher_id': 71
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 144,
        'subject_id': 'SUB_MIP_S4_019',
        'name': 'Analyse numerique',
        'class_name': 'MIP_S4',
        'department_id': 9,
        'teacher_id': 44
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 145,
        'subject_id': 'SUB_MIP_S4_020',
        'name': 'Mecanique quantique',
        'class_name': 'MIP_S4',
        'department_id': 10,
        'teacher_id': 59
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 146,
        'subject_id': 'SUB_MIP_S4_021',
        'name': 'Electromagnetisme',
        'class_name': 'MIP_S4',
        'department_id': 10,
        'teacher_id': 66
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 147,
        'subject_id': 'SUB_MIP_S4_022',
        'name': 'Base de donne BDD',
        'class_name': 'MIP_S4',
        'department_id': 13,
        'teacher_id': 82
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 148,
        'subject_id': 'SUB_MIP_S4_023',
        'name': 'Structure de donne en C',
        'class_name': 'MIP_S4',
        'department_id': 13,
        'teacher_id': 82
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 149,
        'subject_id': 'SUB_MIPC_1_S1_024',
        'name': 'Analyse 1',
        'class_name': 'MIPC_1_S1',
        'department_id': 9,
        'teacher_id': 44
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 150,
        'subject_id': 'SUB_MIPC_1_S1_025',
        'name': 'Algebre 1',
        'class_name': 'MIPC_1_S1',
        'department_id': 9,
        'teacher_id': 61
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 151,
        'subject_id': 'SUB_MIPC_1_S1_026',
        'name': 'Circuit electrique',
        'class_name': 'MIPC_1_S1',
        'department_id': 10,
        'teacher_id': 78
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 152,
        'subject_id': 'SUB_MIPC_1_S1_027',
        'name': 'Electricite',
        'class_name': 'MIPC_1_S1',
        'department_id': 10,
        'teacher_id': 69
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 153,
        'subject_id': 'SUB_MIPC_1_S1_028',
        'name': 'LC 1',
        'class_name': 'MIPC_1_S1',
        'department_id': 14,
        'teacher_id': 63
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 154,
        'subject_id': 'SUB_MIPC_1_S1_029',
        'name': 'Algorithme et Programmation 1',
        'class_name': 'MIPC_1_S1',
        'department_id': 9,
        'teacher_id': 58
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 155,
        'subject_id': 'SUB_MIPC_1_S2_030',
        'name': 'Analyse 2',
        'class_name': 'MIPC_1_S2',
        'department_id': 9,
        'teacher_id': 46
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 156,
        'subject_id': 'SUB_MIPC_1_S2_031',
        'name': 'Algebre 2',
        'class_name': 'MIPC_1_S2',
        'department_id': 9,
        'teacher_id': 60
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 157,
        'subject_id': 'SUB_MIPC_1_S2_032',
        'name': 'Thermodynamique',
        'class_name': 'MIPC_1_S2',
        'department_id': 10,
        'teacher_id': 75
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 158,
        'subject_id': 'SUB_MIPC_1_S2_033',
        'name': 'Mecanique du point',
        'class_name': 'MIPC_1_S2',
        'department_id': 10,
        'teacher_id': 75
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 159,
        'subject_id': 'SUB_MIPC_1_S2_034',
        'name': 'LC 2',
        'class_name': 'MIPC_1_S2',
        'department_id': 14,
        'teacher_id': 63
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 160,
        'subject_id': 'SUB_MIPC_1_S2_035',
        'name': 'Atomistique et thermochimie',
        'class_name': 'MIPC_1_S2',
        'department_id': 12,
        'teacher_id': 67
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 161,
        'subject_id': 'SUB_MIPC_1_S3_036',
        'name': 'Analyse 3',
        'class_name': 'MIPC_1_S3',
        'department_id': 9,
        'teacher_id': 44
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 162,
        'subject_id': 'SUB_MIPC_1_S3_037',
        'name': 'Statistique et proba',
        'class_name': 'MIPC_1_S3',
        'department_id': 9,
        'teacher_id': 73
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 163,
        'subject_id': 'SUB_MIPC_1_S3_038',
        'name': 'Reactivite chimique',
        'class_name': 'MIPC_1_S3',
        'department_id': 12,
        'teacher_id': 52
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 164,
        'subject_id': 'SUB_MIPC_1_S3_039',
        'name': 'LC 3',
        'class_name': 'MIPC_1_S3',
        'department_id': 14,
        'teacher_id': 56
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 165,
        'subject_id': 'SUB_MIPC_1_S3_040',
        'name': 'Mecanique de solide',
        'class_name': 'MIPC_1_S3',
        'department_id': 10,
        'teacher_id': 75
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 166,
        'subject_id': 'SUB_MIPC_1_S3_041',
        'name': 'Chimie organique',
        'class_name': 'MIPC_1_S3',
        'department_id': 12,
        'teacher_id': 67
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 167,
        'subject_id': 'SUB_MIPC_1_S4_042',
        'name': 'Analyse 4',
        'class_name': 'MIPC_1_S4',
        'department_id': 9,
        'teacher_id': 44
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 168,
        'subject_id': 'SUB_MIPC_1_S4_043',
        'name': 'Analyse numerique',
        'class_name': 'MIPC_1_S4',
        'department_id': 9,
        'teacher_id': 50
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 169,
        'subject_id': 'SUB_MIPC_1_S4_044',
        'name': 'Mecanique quantique',
        'class_name': 'MIPC_1_S4',
        'department_id': 10,
        'teacher_id': 75
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 170,
        'subject_id': 'SUB_MIPC_1_S4_045',
        'name': 'Electromagnetisme',
        'class_name': 'MIPC_1_S4',
        'department_id': 10,
        'teacher_id': 78
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 171,
        'subject_id': 'SUB_MIPC_1_S4_046',
        'name': 'Chimie minirale',
        'class_name': 'MIPC_1_S4',
        'department_id': 12,
        'teacher_id': 52
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 172,
        'subject_id': 'SUB_MIPC_1_S4_047',
        'name': 'Relativite restreinte',
        'class_name': 'MIPC_1_S4',
        'department_id': 10,
        'teacher_id': 59
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 173,
        'subject_id': 'SUB_MIPC_2_S1_048',
        'name': 'Analyse 1',
        'class_name': 'MIPC_2_S1',
        'department_id': 9,
        'teacher_id': 71
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 174,
        'subject_id': 'SUB_MIPC_2_S1_049',
        'name': 'Algebre 1',
        'class_name': 'MIPC_2_S1',
        'department_id': 9,
        'teacher_id': 60
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 175,
        'subject_id': 'SUB_MIPC_2_S1_050',
        'name': 'Circuit electrique',
        'class_name': 'MIPC_2_S1',
        'department_id': 10,
        'teacher_id': 75
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 176,
        'subject_id': 'SUB_MIPC_2_S1_051',
        'name': 'Electricite',
        'class_name': 'MIPC_2_S1',
        'department_id': 10,
        'teacher_id': 59
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 177,
        'subject_id': 'SUB_MIPC_2_S1_052',
        'name': 'LC 1',
        'class_name': 'MIPC_2_S1',
        'department_id': 14,
        'teacher_id': 54
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 178,
        'subject_id': 'SUB_MIPC_2_S1_053',
        'name': 'Algorithme et Programmation 1',
        'class_name': 'MIPC_2_S1',
        'department_id': 9,
        'teacher_id': 76
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 179,
        'subject_id': 'SUB_MIPC_2_S2_054',
        'name': 'Analyse 2',
        'class_name': 'MIPC_2_S2',
        'department_id': 9,
        'teacher_id': 61
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 180,
        'subject_id': 'SUB_MIPC_2_S2_055',
        'name': 'Algebre 2',
        'class_name': 'MIPC_2_S2',
        'department_id': 9,
        'teacher_id': 46
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 181,
        'subject_id': 'SUB_MIPC_2_S2_056',
        'name': 'Thermodynamique',
        'class_name': 'MIPC_2_S2',
        'department_id': 10,
        'teacher_id': 78
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 182,
        'subject_id': 'SUB_MIPC_2_S2_057',
        'name': 'Mecanique du point',
        'class_name': 'MIPC_2_S2',
        'department_id': 10,
        'teacher_id': 78
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 183,
        'subject_id': 'SUB_MIPC_2_S2_058',
        'name': 'LC 2',
        'class_name': 'MIPC_2_S2',
        'department_id': 14,
        'teacher_id': 45
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 184,
        'subject_id': 'SUB_MIPC_2_S2_059',
        'name': 'Atomistique et thermochimie',
        'class_name': 'MIPC_2_S2',
        'department_id': 12,
        'teacher_id': 77
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 185,
        'subject_id': 'SUB_MIPC_2_S3_060',
        'name': 'Analyse 3',
        'class_name': 'MIPC_2_S3',
        'department_id': 9,
        'teacher_id': 61
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 186,
        'subject_id': 'SUB_MIPC_2_S3_061',
        'name': 'Statistique et proba',
        'class_name': 'MIPC_2_S3',
        'department_id': 9,
        'teacher_id': 60
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 187,
        'subject_id': 'SUB_MIPC_2_S3_062',
        'name': 'Reactivite chimique',
        'class_name': 'MIPC_2_S3',
        'department_id': 12,
        'teacher_id': 57
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 188,
        'subject_id': 'SUB_MIPC_2_S3_063',
        'name': 'LC 3',
        'class_name': 'MIPC_2_S3',
        'department_id': 14,
        'teacher_id': 54
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 189,
        'subject_id': 'SUB_MIPC_2_S3_064',
        'name': 'Mecanique de solide',
        'class_name': 'MIPC_2_S3',
        'department_id': 10,
        'teacher_id': 78
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 190,
        'subject_id': 'SUB_MIPC_2_S3_065',
        'name': 'Chimie organique',
        'class_name': 'MIPC_2_S3',
        'department_id': 12,
        'teacher_id': 72
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 191,
        'subject_id': 'SUB_MIPC_2_S4_066',
        'name': 'Analyse 4',
        'class_name': 'MIPC_2_S4',
        'department_id': 9,
        'teacher_id': 50
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 192,
        'subject_id': 'SUB_MIPC_2_S4_067',
        'name': 'Analyse numerique',
        'class_name': 'MIPC_2_S4',
        'department_id': 9,
        'teacher_id': 65
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 193,
        'subject_id': 'SUB_MIPC_2_S4_068',
        'name': 'Mecanique quantique',
        'class_name': 'MIPC_2_S4',
        'department_id': 10,
        'teacher_id': 59
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 194,
        'subject_id': 'SUB_MIPC_2_S4_069',
        'name': 'Electromagnetisme',
        'class_name': 'MIPC_2_S4',
        'department_id': 10,
        'teacher_id': 66
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 195,
        'subject_id': 'SUB_MIPC_2_S4_070',
        'name': 'Chimie minirale',
        'class_name': 'MIPC_2_S4',
        'department_id': 12,
        'teacher_id': 47
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 196,
        'subject_id': 'SUB_MIPC_2_S4_071',
        'name': 'Relativite restreinte',
        'class_name': 'MIPC_2_S4',
        'department_id': 10,
        'teacher_id': 78
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 197,
        'subject_id': 'SUB_BCG_S1_072',
        'name': 'Analyse 1',
        'class_name': 'BCG_S1',
        'department_id': 9,
        'teacher_id': 71
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 198,
        'subject_id': 'SUB_BCG_S1_073',
        'name': 'Algebre 1',
        'class_name': 'BCG_S1',
        'department_id': 9,
        'teacher_id': 73
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 199,
        'subject_id': 'SUB_BCG_S1_074',
        'name': 'Circuit electrique',
        'class_name': 'BCG_S1',
        'department_id': 10,
        'teacher_id': 75
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 200,
        'subject_id': 'SUB_BCG_S1_075',
        'name': 'Electricite',
        'class_name': 'BCG_S1',
        'department_id': 10,
        'teacher_id': 75
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 201,
        'subject_id': 'SUB_BCG_S1_076',
        'name': 'LC 1',
        'class_name': 'BCG_S1',
        'department_id': 14,
        'teacher_id': 63
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 202,
        'subject_id': 'SUB_BCG_S1_077',
        'name': 'Algorithme et Programmation 1',
        'class_name': 'BCG_S1',
        'department_id': 9,
        'teacher_id': 64
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 203,
        'subject_id': 'SUB_BCG_S2_078',
        'name': 'Analyse 2',
        'class_name': 'BCG_S2',
        'department_id': 9,
        'teacher_id': 71
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 204,
        'subject_id': 'SUB_BCG_S2_079',
        'name': 'Algebre 2',
        'class_name': 'BCG_S2',
        'department_id': 9,
        'teacher_id': 60
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 205,
        'subject_id': 'SUB_BCG_S2_080',
        'name': 'Thermodynamique',
        'class_name': 'BCG_S2',
        'department_id': 10,
        'teacher_id': 69
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 206,
        'subject_id': 'SUB_BCG_S2_081',
        'name': 'Mecanique du point',
        'class_name': 'BCG_S2',
        'department_id': 10,
        'teacher_id': 78
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 207,
        'subject_id': 'SUB_BCG_S2_082',
        'name': 'LC 2',
        'class_name': 'BCG_S2',
        'department_id': 14,
        'teacher_id': 63
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 208,
        'subject_id': 'SUB_BCG_S2_083',
        'name': 'Atomistique et thermochimie',
        'class_name': 'BCG_S2',
        'department_id': 12,
        'teacher_id': 47
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 209,
        'subject_id': 'SUB_BCG_S3_084',
        'name': 'Analyse 3',
        'class_name': 'BCG_S3',
        'department_id': 9,
        'teacher_id': 44
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 210,
        'subject_id': 'SUB_BCG_S3_085',
        'name': 'Statistique et proba',
        'class_name': 'BCG_S3',
        'department_id': 9,
        'teacher_id': 46
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 211,
        'subject_id': 'SUB_BCG_S3_086',
        'name': 'Reactivite chimique',
        'class_name': 'BCG_S3',
        'department_id': 12,
        'teacher_id': 52
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 212,
        'subject_id': 'SUB_BCG_S3_087',
        'name': 'LC 3',
        'class_name': 'BCG_S3',
        'department_id': 14,
        'teacher_id': 74
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 213,
        'subject_id': 'SUB_BCG_S3_088',
        'name': 'Mecanique de solide',
        'class_name': 'BCG_S3',
        'department_id': 10,
        'teacher_id': 59
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 214,
        'subject_id': 'SUB_BCG_S3_089',
        'name': 'Chimie organique',
        'class_name': 'BCG_S3',
        'department_id': 12,
        'teacher_id': 67
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 215,
        'subject_id': 'SUB_BCG_S4_090',
        'name': 'Analyse 4',
        'class_name': 'BCG_S4',
        'department_id': 9,
        'teacher_id': 73
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 216,
        'subject_id': 'SUB_BCG_S4_091',
        'name': 'Analyse numerique',
        'class_name': 'BCG_S4',
        'department_id': 9,
        'teacher_id': 73
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 217,
        'subject_id': 'SUB_BCG_S4_092',
        'name': 'Mecanique quantique',
        'class_name': 'BCG_S4',
        'department_id': 10,
        'teacher_id': 78
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 218,
        'subject_id': 'SUB_BCG_S4_093',
        'name': 'Electromagnetisme',
        'class_name': 'BCG_S4',
        'department_id': 10,
        'teacher_id': 75
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 219,
        'subject_id': 'SUB_BCG_S4_094',
        'name': 'Chimie minirale',
        'class_name': 'BCG_S4',
        'department_id': 12,
        'teacher_id': 57
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 220,
        'subject_id': 'SUB_BCG_S4_095',
        'name': 'Relativite restreinte',
        'class_name': 'BCG_S4',
        'department_id': 10,
        'teacher_id': 69
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 221,
        'subject_id': 'SUB_GEGM_S1_096',
        'name': 'Analyse 1',
        'class_name': 'GEGM_S1',
        'department_id': 9,
        'teacher_id': 60
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 222,
        'subject_id': 'SUB_GEGM_S1_097',
        'name': 'Algebre 1',
        'class_name': 'GEGM_S1',
        'department_id': 9,
        'teacher_id': 44
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 223,
        'subject_id': 'SUB_GEGM_S1_098',
        'name': 'Circuit electrique',
        'class_name': 'GEGM_S1',
        'department_id': 10,
        'teacher_id': 78
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 224,
        'subject_id': 'SUB_GEGM_S1_099',
        'name': 'Electricite',
        'class_name': 'GEGM_S1',
        'department_id': 10,
        'teacher_id': 78
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 225,
        'subject_id': 'SUB_GEGM_S1_100',
        'name': 'LC 1',
        'class_name': 'GEGM_S1',
        'department_id': 14,
        'teacher_id': 56
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 226,
        'subject_id': 'SUB_GEGM_S1_101',
        'name': 'Algorithme et Programmation 1',
        'class_name': 'GEGM_S1',
        'department_id': 9,
        'teacher_id': 58
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 227,
        'subject_id': 'SUB_GEGM_S2_102',
        'name': 'Analyse 2',
        'class_name': 'GEGM_S2',
        'department_id': 9,
        'teacher_id': 46
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 228,
        'subject_id': 'SUB_GEGM_S2_103',
        'name': 'Algebre 2',
        'class_name': 'GEGM_S2',
        'department_id': 9,
        'teacher_id': 50
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 229,
        'subject_id': 'SUB_GEGM_S2_104',
        'name': 'Thermodynamique',
        'class_name': 'GEGM_S2',
        'department_id': 10,
        'teacher_id': 59
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 230,
        'subject_id': 'SUB_GEGM_S2_105',
        'name': 'Mecanique du point',
        'class_name': 'GEGM_S2',
        'department_id': 10,
        'teacher_id': 78
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 231,
        'subject_id': 'SUB_GEGM_S2_106',
        'name': 'LC 2',
        'class_name': 'GEGM_S2',
        'department_id': 14,
        'teacher_id': 63
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 232,
        'subject_id': 'SUB_GEGM_S2_107',
        'name': 'Atomistique et thermochimie',
        'class_name': 'GEGM_S2',
        'department_id': 12,
        'teacher_id': 49
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 233,
        'subject_id': 'SUB_GEGM_S3_108',
        'name': 'Analyse 3',
        'class_name': 'GEGM_S3',
        'department_id': 9,
        'teacher_id': 50
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 234,
        'subject_id': 'SUB_GEGM_S3_109',
        'name': 'Statistique et proba',
        'class_name': 'GEGM_S3',
        'department_id': 9,
        'teacher_id': 46
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 235,
        'subject_id': 'SUB_GEGM_S3_110',
        'name': 'Reactivite chimique',
        'class_name': 'GEGM_S3',
        'department_id': 12,
        'teacher_id': 57
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 236,
        'subject_id': 'SUB_GEGM_S3_111',
        'name': 'LC 3',
        'class_name': 'GEGM_S3',
        'department_id': 14,
        'teacher_id': 63
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 237,
        'subject_id': 'SUB_GEGM_S3_112',
        'name': 'Mecanique de solide',
        'class_name': 'GEGM_S3',
        'department_id': 10,
        'teacher_id': 75
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 238,
        'subject_id': 'SUB_GEGM_S3_113',
        'name': 'Algo et program 2',
        'class_name': 'GEGM_S3',
        'department_id': 9,
        'teacher_id': 54
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 239,
        'subject_id': 'SUB_GEGM_S4_114',
        'name': 'Analyse 4',
        'class_name': 'GEGM_S4',
        'department_id': 9,
        'teacher_id': 65
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 240,
        'subject_id': 'SUB_GEGM_S4_115',
        'name': 'Analyse numerique',
        'class_name': 'GEGM_S4',
        'department_id': 9,
        'teacher_id': 44
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 241,
        'subject_id': 'SUB_GEGM_S4_116',
        'name': 'Mecanique quantique',
        'class_name': 'GEGM_S4',
        'department_id': 10,
        'teacher_id': 69
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 242,
        'subject_id': 'SUB_GEGM_S4_117',
        'name': 'Electromagnetisme',
        'class_name': 'GEGM_S4',
        'department_id': 10,
        'teacher_id': 59
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 243,
        'subject_id': 'SUB_GEGM_S4_118',
        'name': 'Base de donne BDD',
        'class_name': 'GEGM_S4',
        'department_id': 13,
        'teacher_id': 58
    }},
    {'model': 'faculty.Subject', 'fields': {
        'id': 244,
        'subject_id': 'SUB_GEGM_S4_119',
        'name': 'Structure de donne en C',
        'class_name': 'GEGM_S4',
        'department_id': 13,
        'teacher_id': 62
    }}
    ]
    
    print(f"\n[Data Migration] Loading {len(data)} entries for 0009_load_faculty_data...")
    for item in data:
        app_label, model_name = item['model'].split('.')
        Model = apps.get_model(app_label, model_name)
        fields = item['fields']
        # update_or_create to ensure no duplicates
        pk_val = fields.pop('id', None)
        if pk_val:
            Model.objects.update_or_create(id=pk_val, defaults=fields)
        else:
            Model.objects.create(**fields)

class Migration(migrations.Migration):
    dependencies = [
        ('home_auth', '0008_load_auth_data'),
        ('faculty', '0007_delete_book'),
    ]
    operations = [
        migrations.RunPython(load_data),
    ]
